name: reuse

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install reuse
      run: |
        python -m pip install --upgrade pip
        pip install reuse
    - name: Analysing the code with reuse
      run: reuse lint
